#![allow(dead_code)]

/// Simple static two-language dictionary. `Lang::ID` is the default.
pub struct Lang {
    pub by: &'static str,

    pub nav_home: &'static str,
    pub nav_versions: &'static str,
    pub nav_instances: &'static str,
    pub nav_accounts: &'static str,
    pub nav_settings: &'static str,
    pub nav_console: &'static str,

    pub active_version: &'static str,
    pub memory: &'static str,
    pub installed: &'static str,
    pub not_installed: &'static str,

    pub home_ready: &'static str,
    pub waiting_task: &'static str,
    pub need_login_hint: &'static str,
    pub need_version_hint: &'static str,
    pub play: &'static str,
    pub install: &'static str,
    pub stop: &'static str,
    pub active_account: &'static str,
    pub manage: &'static str,
    pub no_active_account: &'static str,
    pub sign_in: &'static str,
    pub mc_version: &'static str,
    pub status: &'static str,

    pub search_versions: &'static str,
    pub reload: &'static str,
    pub releases_only_hint: &'static str,
    pub loading_versions: &'static str,
    pub empty_versions: &'static str,
    pub use_version: &'static str,
    pub pick_version: &'static str,
    pub client_mods: &'static str,
    pub client_mods_mc: &'static str,
    pub client_mods_load: &'static str,
    pub failed_fetch_loaders: &'static str,

    pub saved_accounts: &'static str,
    pub no_saved_accounts: &'static str,
    pub remove: &'static str,
    pub refresh_token: &'static str,
    pub activate: &'static str,
    pub active_badge: &'static str,
    pub ely_oauth: &'static str,
    pub ely_password: &'static str,
    pub token_expired: &'static str,
    pub token_valid_min: &'static str,
    pub token_expires_on: &'static str,
    pub unit_day: &'static str,
    pub unit_hour: &'static str,
    pub unit_min: &'static str,
    pub unit_sec: &'static str,
    pub add_account: &'static str,
    pub oauth_title: &'static str,
    pub oauth_desc: &'static str,
    pub login_with_ely: &'static str,
    pub login_ely_account: &'static str,
    pub register_ely: &'static str,
    pub offline_account: &'static str,
    pub offline_desc: &'static str,
    pub offline_name: &'static str,
    pub add_offline: &'static str,
    pub offline_name_invalid: &'static str,
    pub offline_locked: &'static str,
    pub password_title: &'static str,
    pub email_or_username: &'static str,
    pub password: &'static str,
    pub show_password: &'static str,
    pub fill_credentials: &'static str,

    pub versions_label: &'static str,
    pub show_all_versions: &'static str,
    pub show_custom_clients: &'static str,
    pub custom_clients_hint: &'static str,
    pub kind_custom: &'static str,
    pub java_label: &'static str,
    pub auto_download_java: &'static str,
    pub java_path: &'static str,
    pub detect: &'static str,
    pub clear: &'static str,
    pub download_java_now: &'static str,
    pub needs_java: &'static str,
    pub java_saved: &'static str,
    pub java_not_found: &'static str,
    pub launch_label: &'static str,
    pub memory_label: &'static str,
    pub resolution: &'static str,
    pub authlib_url_label: &'static str,
    pub authlib_hint: &'static str,
    pub extra_jvm_args_label: &'static str,
    pub extra_jvm_args_hint: &'static str,
    pub reset_defaults: &'static str,
    pub language_label: &'static str,
    pub language_choice: &'static str,
    pub indonesian: &'static str,
    pub english: &'static str,

    pub font_label: &'static str,
    pub font_choice: &'static str,
    pub font_monogram: &'static str,
    pub font_system: &'static str,

    pub instances_title: &'static str,
    pub new_instance: &'static str,
    pub select: &'static str,
    pub edit: &'static str,
    pub delete: &'static str,
    pub no_instances: &'static str,
    pub no_instances_hint: &'static str,
    pub instance_name: &'static str,
    pub save: &'static str,
    pub cancel: &'static str,
    pub name_taken: &'static str,
    pub cannot_delete_last: &'static str,
    pub instance_created: &'static str,
    pub instance_updated: &'static str,
    pub instance_deleted: &'static str,
    pub no_instance_selected: &'static str,
    pub switch_instance: &'static str,
    pub version_changed_reinstall: &'static str,
    pub choose_instance: &'static str,
    pub latest_instance: &'static str,
    pub latest_badge: &'static str,
    pub latest_hint: &'static str,
    pub latest_no_edit: &'static str,
    pub delete_data: &'static str,
    pub check_repair: &'static str,
    pub repairing: &'static str,
    pub repair_ok: &'static str,
    pub version_delete_title: &'static str,
    pub version_delete_body: &'static str,
    pub tab_all: &'static str,
    pub tab_downloaded: &'static str,
    pub empty_downloaded: &'static str,
    pub create_instance_hint: &'static str,
    pub version_unavailable: &'static str,
    pub already_running: &'static str,
    pub version_deleted: &'static str,
    pub latest_key_reserved: &'static str,
    pub update_available: &'static str,
    pub update_available_body: &'static str,
    pub installed_current: &'static str,
    pub continue_playing: &'static str,
    pub update_now: &'static str,

    pub console_clear: &'static str,
    pub auto_scroll: &'static str,

    pub toast_ok: &'static str,
    pub toast_err: &'static str,
    pub toast_info: &'static str,
    pub task_busy: &'static str,
    pub game_running: &'static str,
    pub game_stopped: &'static str,
    pub game_exited: &'static str,
    pub account_added: &'static str,
    pub account_active: &'static str,
    pub account_removed: &'static str,
    pub verify_page: &'static str,
    pub copy: &'static str,
    pub open_verify_page: &'static str,
    pub oauth_auto: &'static str,
    pub login_cancelled: &'static str,
    pub twofa_title: &'static str,
    pub twofa_hint: &'static str,
    pub submit: &'static str,
    pub twofa_empty: &'static str,
    pub select_version_first: &'static str,
    pub login_required: &'static str,
    pub stop_game: &'static str,
    pub saved: &'static str,
    pub save_failed: &'static str,
    pub installing_version: &'static str,
    pub done_version: &'static str,

    pub version_picked: &'static str,
    pub starting: &'static str,
    pub verify_win_title: &'static str,
    pub cannot_open_browser: &'static str,
    pub console_save: &'static str,
    pub log_saved: &'static str,
    pub log_copied: &'static str,

    pub init_failed: &'static str,
    pub fetching_versions: &'static str,
    pub found_versions: &'static str,
    pub login_success: &'static str,
    pub token_updated: &'static str,
    pub checking_latest: &'static str,
    pub newer_available: &'static str,
    pub choice_dialog_closed: &'static str,
    pub continuing_version: &'static str,
    pub update_cancelled: &'static str,
    pub no_active_instance_err: &'static str,
    pub no_version_selected_err: &'static str,
    pub java_too_old: &'static str,
    pub java_missing: &'static str,
    pub using_java: &'static str,
    pub repairing_install: &'static str,
    pub launch_args: &'static str,
    pub game_launched_pid: &'static str,
    pub installing_version_log: &'static str,
    pub checking_assets: &'static str,
    pub java_runtime_installed: &'static str,
    pub downloading_java: &'static str,
    pub account_type_password: &'static str,
    pub account_type_oauth: &'static str,

    pub failed_connect_ely: &'static str,
    pub failed_fetch_account: &'static str,
    pub failed_start_login: &'static str,
    pub failed_refresh_token: &'static str,
    pub failed_fetch_avatar: &'static str,
    pub failed_read_avatar: &'static str,
    pub login_failed: &'static str,
    pub code_expired: &'static str,
    pub login_denied: &'static str,
    pub failed_fetch_versions: &'static str,
    pub failed_read_versions: &'static str,
    pub failed_download_version: &'static str,
    pub failed_parse_version: &'static str,
    pub failed_download_authlib: &'static str,
    pub failed_open_native_jar: &'static str,
    pub failed_java_version: &'static str,
    pub cannot_read_java_version: &'static str,
    pub no_java_for_platform: &'static str,
    pub no_matching_runtime: &'static str,
    pub no_manifest_for: &'static str,
    pub failed_launch_game: &'static str,
    pub failed_wait_game: &'static str,
    pub no_launch_args: &'static str,
    pub failed_download: &'static str,
    pub failed_read_response: &'static str,
    pub failed_save_download: &'static str,
    pub no_url_available: &'static str,
    pub version_not_in_manifest: &'static str,
    pub inherits_unsupported: &'static str,
    pub asset_progress: &'static str,
    pub invalid_archive: &'static str,
    pub downloading_client_jar: &'static str,
    pub extracting_natives: &'static str,
    pub server_status: &'static str,
    pub sha1_mismatch: &'static str,
    pub failed_read_bytes: &'static str,
    pub all_urls_failed: &'static str,
    pub asset_stage: &'static str,
    pub invalid_asset_index: &'static str,
    pub invalid_java_version_format: &'static str,
    pub java_index_empty: &'static str,
    pub invalid_java_runtime_data: &'static str,
    pub invalid_runtime_data: &'static str,
    pub invalid_runtime_manifest: &'static str,
    pub runtime_manifest_no_files: &'static str,
    pub failed_fetch_account_status: &'static str,
    pub access_denied: &'static str,
    pub open_page_code: &'static str,
    pub token_received_fetching_profile: &'static str,
    pub no_refresh_token: &'static str,
    pub login_request_denied: &'static str,
    pub wrong_credentials: &'static str,
    pub unknown_auth_response: &'static str,
    pub no_minecraft_profile: &'static str,
    pub no_client_token: &'static str,
    pub invalid_token: &'static str,
    pub refresh_failed: &'static str,
    pub unknown_refresh_response: &'static str,
    pub invalid_avatar_image: &'static str,
    pub no_data_dir: &'static str,
    pub account_uses_2fa: &'static str,
    pub enter_verify_code: &'static str,
    pub java_mismatch: &'static str,
    pub java_mode_label: &'static str,
    pub java_mode_auto: &'static str,
    pub java_mode_manual: &'static str,
    pub auto_java_desc: &'static str,
    pub browse: &'static str,
    pub open_logs_folder: &'static str,
    pub open_folder: &'static str,
    pub open_failed: &'static str,
    pub game_dir_label: &'static str,
    pub game_dir_path_label: &'static str,
    pub game_dir_launcher: &'static str,
    pub game_dir_original: &'static str,
    pub game_dir_custom: &'static str,
    pub game_dir_hint: &'static str,
    pub browse_folder: &'static str,
    pub data_dir_label: &'static str,
    pub data_dir_choice: &'static str,
    pub data_dir_launcher: &'static str,
    pub data_dir_original: &'static str,
    pub data_dir_custom: &'static str,
    pub data_dir_path_label: &'static str,
    pub data_dir_hint: &'static str,
    pub data_dir_current: &'static str,
    pub data_dir_changed: &'static str,
    pub vanilla_branding_label: &'static str,
    pub vanilla_branding_hint: &'static str,
    pub delete_confirm_title: &'static str,
    pub delete_confirm_body: &'static str,
    pub delete_confirm_also_folder: &'static str,
    pub delete_folder_locked: &'static str,
    pub folder_deleted: &'static str,
}

impl Lang {
    pub const ID: &'static Lang = &Lang {
        by: "By StievenW",

        nav_home: "Beranda",
        nav_versions: "Versi",
        nav_instances: "Instansi",
        nav_accounts: "Akun",
        nav_settings: "Pengaturan",
        nav_console: "Konsol",

        active_version: "VERSI AKTIF",
        memory: "MEMORI",
        installed: "Terpasang",
        not_installed: "Belum terpasang",

        home_ready: "Siap.",
        waiting_task: "Menunggu proses selesai...",
        need_login_hint: "Masuk akun Ely.by untuk bermain (menu Akun).",
        need_version_hint: "Pilih versi terlebih dahulu.",
        play: "MAIN",
        install: "PASANG",
        stop: "HENTIKAN",
        active_account: "AKUN AKTIF",
        manage: "Kelola",
        no_active_account: "Belum ada akun aktif.",
        sign_in: "Masuk",
        mc_version: "VERSI MINECRAFT",
        status: "STATUS",

        search_versions: "Cari versi...",
        reload: "Muat Ulang",
        releases_only_hint: "Menampilkan rilis saja. Aktifkan 'Semua versi' di Pengaturan untuk melihat build, beta, dan snapshot.",
        loading_versions: "Memuat daftar versi...",
        empty_versions: "Daftar versi kosong.",
        use_version: "Pakai",
        pick_version: "Pasang",
        client_mods: "CLIENT MODS",
        client_mods_mc: "Versi Minecraft:",
        client_mods_load: "Muat daftar",
        failed_fetch_loaders: "Gagal memuat daftar loader.",

        saved_accounts: "AKUN TERSIMPAN",
        no_saved_accounts: "Belum ada akun tersimpan.",
        remove: "Hapus",
        refresh_token: "Perbarui Token",
        activate: "Aktifkan",
        active_badge: "AKTIF",
        ely_oauth: "Ely.by (OAuth)",
        ely_password: "Ely.by (Kata sandi)",
        token_expired: "token kedaluwarsa",
        token_valid_min: "token valid sekitar {} mnt",
        token_expires_on: "Kedaluwarsa {} (sisa {})",
        unit_day: "hari",
        unit_hour: "jam",
        unit_min: "mnt",
        unit_sec: "dtk",
        add_account: "TAMBAH AKUN",
        oauth_title: "Login dengan Ely.by (OAuth)",
        oauth_desc: "Menggunakan kode verifikasi (device flow). Client ID sudah tertanam di launcher.",
        login_with_ely: "Login dengan Ely.by",
        login_ely_account: "Masuk dengan akun Ely.by",
        register_ely: "Belum punya akun Ely.by? Daftar",
        offline_account: "Akun Offline",
        offline_desc: "Wajib login dengan akun Ely.by terlebih dahulu.",
        offline_name: "Nama pemain",
        add_offline: "Tambah Akun Offline",
        offline_name_invalid: "Nama pemain tidak valid (3-16 karakter, tanpa spasi).",
        offline_locked: "Terkunci - butuh minimal satu akun Ely.by yang valid.",
        password_title: "Login dengan email / kata sandi",
        email_or_username: "Email atau username",
        password: "Kata sandi",
        show_password: "Tampilkan kata sandi",
        fill_credentials: "Isi email/username dan kata sandi.",

        versions_label: "VERSI",
        show_all_versions: "Tampilkan semua versi (build, beta, snapshot)",
        show_custom_clients: "Tampilkan semua custom client lengkap",
        custom_clients_hint: "Menampilkan client mod / custom client yang terpasang di folder versions launcher (di luar daftar resmi Mojang).",
        kind_custom: "custom",
        java_label: "JAVA",
        auto_download_java: "Unduh otomatis runtime Java bila tidak ditemukan",
        java_path: "Java path:",
        detect: "Deteksi",
        clear: "Bersihkan",
        download_java_now: "Unduh Java Sekarang",
        needs_java: "Versi ini butuh Java {}+",
        java_saved: "Java {} ditemukan dan disimpan ke pengaturan.",
        java_not_found: "Java yang memenuhi syarat (Java {}+) tidak ditemukan. Pasang Java atau gunakan unduh otomatis.",
        launch_label: "PELUNCURAN",
        memory_label: "Memori:",
        resolution: "Resolusi:",
        authlib_url_label: "authlib URL:",
        authlib_hint: "Argumen -javaagent authlib-injector",
        extra_jvm_args_label: "Argumen JVM tambahan:",
        extra_jvm_args_hint: "mis. -Duser.language=id",
        reset_defaults: "Reset ke Default",
        language_label: "BAHASA",
        language_choice: "Bahasa aplikasi:",
        indonesian: "Indonesia",
        english: "English",
        font_label: "FONT",
        font_choice: "Font aplikasi:",
        font_monogram: "Monogram (Bitmap)",
        font_system: "Normal (Sistem)",

        instances_title: "INSTANSI",
        new_instance: "Buat Instansi Baru",
        select: "Pilih",
        edit: "Ubah",
        delete: "Hapus",
        no_instances: "Belum ada instansi.",
        no_instances_hint: "Buat satu untuk mulai bermain.",
        instance_name: "Nama instansi:",
        save: "Simpan",
        cancel: "Batal",
        name_taken: "Nama instansi sudah dipakai.",
        cannot_delete_last: "Tidak bisa menghapus instansi terakhir.",
        instance_created: "Instansi dibuat.",
        instance_updated: "Instansi diperbarui.",
        instance_deleted: "Instansi dihapus.",
        no_instance_selected: "Pilih atau buat instansi terlebih dahulu.",
        switch_instance: "Ganti",
        version_changed_reinstall: "Versi berubah, akan dipasang ulang saat MAIN ditekan.",
        choose_instance: "Pilih instansi:",
        latest_instance: "Terbaru (Release)",
        latest_badge: "RELEASE - AUTO",
        latest_hint: "Otomatis memakai rilis terbaru setiap kali MAIN.",
        latest_no_edit: "Versi tidak dapat diubah (selalu rilis terbaru).",
        delete_data: "Hapus Data",
        check_repair: "Periksa & Perbaiki",
        repairing: "Memeriksa dan memperbaiki versi...",
        repair_ok: "Versi lengkap dan valid, tidak ada yang rusak.",
        version_delete_title: "Hapus versi?",
        version_delete_body: "Data versi '{}' (JSON, jar, dan file versi) akan dihapus permanen. Lanjutkan?",
        tab_all: "Semua",
        tab_downloaded: "Terunduh",
        empty_downloaded: "Belum ada versi terunduh.",
        create_instance_hint: "Buat instansi sendiri untuk memilih versi bebas (menu Instansi).",
        version_unavailable: "Versi belum tersedia. Cek koneksi lalu muat ulang daftar versi.",
        already_running: "HanaLauncher sudah berjalan. Tutup instance yang sudah ada terlebih dahulu.",
        version_deleted: "Data versi dihapus.",
        latest_key_reserved: "Nama 'latest' dicadangkan untuk instansi terbaru.",
        update_available: "Versi terbaru tersedia",
        update_available_body:
            "Versi {} tersedia. Lanjut main dengan versi yang sudah terpasang atau update sekarang?",
        installed_current: "Versi terpasang saat ini: {}",
        continue_playing: "Lanjut main ({} )",
        update_now: "Update sekarang",

        console_clear: "Bersihkan",
        auto_scroll: "Auto-scroll",

        toast_ok: "Berhasil",
        toast_err: "Gagal",
        toast_info: "Info",
        task_busy: "Sedang ada tugas lain yang berjalan.",
        game_running: "Game berjalan (PID {}).",
        game_stopped: "Menghentikan game...",
        game_exited: "Game berhenti dengan kode {}.",
        account_added: "Akun ditambahkan.",
        account_active: "Akun aktif: {}",
        account_removed: "Akun dihapus.",
        verify_page: "Masukkan kode verifikasi di halaman Ely.by.",
        copy: "Salin",
        open_verify_page: "Buka halaman verifikasi",
        oauth_auto: "Login selesai otomatis setelah kode dikonfirmasi di halaman tersebut.",
        login_cancelled: "Login dibatalkan.",
        twofa_title: "Autentikasi dua faktor (2FA)",
        twofa_hint: "Masukkan kode dari aplikasi autentikator Anda:",
        submit: "Kirim",
        twofa_empty: "Kode 2FA kosong.",
        select_version_first: "Pilih versi terlebih dahulu.",
        login_required: "Login dulu untuk bermain (halaman Akun).",
        stop_game: "Menghentikan game...",
        saved: "Pengaturan disimpan.",
        save_failed: "Gagal menyimpan: {}",
        installing_version: "Memasang versi...",
        done_version: "Versi selesai dipasang.",

        version_picked: "Versi terpilih: {}",
        starting: "Memulai...",
        verify_win_title: "Login Ely.by - Verifikasi",
        cannot_open_browser: "Tidak dapat membuka browser.",
        console_save: "Simpan Log",
        log_saved: "Log tersimpan di {}",
        log_copied: "Log disalin ke clipboard.",

        init_failed: "Inisialisasi gagal: {}",
        fetching_versions: "Mengambil daftar versi Minecraft...",
        found_versions: "Ditemukan {} versi.",
        login_success: "Login berhasil sebagai {}",
        token_updated: "Token diperbarui untuk {}",
        checking_latest: "Memeriksa rilis terbaru...",
        newer_available: "Versi terbaru {} tersedia (terpasang: {}).",
        choice_dialog_closed: "Dialog pilihan versi ditutup, pembaruan dibatalkan.",
        continuing_version: "Melanjutkan dengan versi {}.",
        update_cancelled: "Pembaruan versi dibatalkan.",
        no_active_instance_err: "Tidak ada instansi aktif",
        no_version_selected_err: "Tidak ada versi yang dipilih",
        java_too_old: "Java terdeteksi (major {}) terlalu tua untuk versi ini (butuh {}), mencari yang lain...",
        java_missing: "Java tidak ditemukan. Pasang Java {}+ atau aktifkan unduh otomatis Java di Pengaturan.",
        using_java: "Menggunakan Java {}: {}",
        repairing_install: "Versi belum terpasang lengkap, memperbaiki instalasi...",
        launch_args: "Argumen peluncuran:",
        game_launched_pid: "Game diluncurkan (PID {}).",
        installing_version_log: "Memasang versi {}...",
        checking_assets: "Memeriksa asset index '{}'...",
        java_runtime_installed: "Java runtime sudah terinstal: {}",
        downloading_java: "Mengunduh Java runtime {} (Java {}+)...",
        account_type_password: "{} (Ely.by - kata sandi)",
        account_type_oauth: "{} (Ely.by - OAuth)",

        failed_connect_ely: "Gagal menghubungi server token Ely.by",
        failed_fetch_account: "Gagal mengambil info akun Ely.by",
        failed_start_login: "Gagal memulai login Ely.by (device code)",
        failed_refresh_token: "Gagal memperbarui token Ely.by",
        failed_fetch_avatar: "Gagal mengunduh avatar",
        failed_read_avatar: "Gagal membaca avatar",
        login_failed: "Login gagal: {}",
        code_expired: "Kode verifikasi kedaluwarsa. Silakan coba login lagi.",
        login_denied: "Login ditolak: {}",
        failed_fetch_versions: "Gagal mengambil daftar versi Minecraft",
        failed_read_versions: "Gagal membaca daftar versi",
        failed_download_version: "Gagal mengunduh data versi {}",
        failed_parse_version: "Format data versi {} tidak dikenal",
        failed_download_authlib: "Gagal mengunduh authlib-injector",
        failed_open_native_jar: "Gagal membuka native jar",
        failed_java_version: "Gagal menjalankan java -version",
        cannot_read_java_version: "Tidak dapat membaca versi Java",
        no_java_for_platform: "Tidak ada Java runtime untuk platform {}",
        no_matching_runtime: "Tidak ada runtime yang cocok",
        no_manifest_for: "Tidak ada manifest untuk {}",
        failed_launch_game: "Gagal meluncurkan proses game",
        failed_wait_game: "Gagal menunggu proses game",
        no_launch_args: "Versi ini tidak memiliki definisi argumen peluncuran",
        failed_download: "Gagal mengunduh: {}",
        failed_read_response: "Gagal membaca respons: {}",
        failed_save_download: "Gagal menyimpan {}",
        no_url_available: "Tidak ada URL yang tersedia",
        version_not_in_manifest: "Versi {} tidak ditemukan di daftar versi Mojang",
        inherits_unsupported: "Versi {} mewarisi versi lain (versi mod) dan belum didukung secara langsung.",
        asset_progress: "  Aset [{}/{}]",
        invalid_archive: "Native jar bukan arsip valid",
        downloading_client_jar: "Mengunduh client jar...",
        extracting_natives: "Mengekstrak native libraries...",
        server_status: "Server mengembalikan status {} untuk {}",
        sha1_mismatch: "Checksum SHA1 tidak cocok untuk {} (harap {}, didapat {})",
        failed_read_bytes: "Gagal membaca respons",
        all_urls_failed: "Semua URL gagal",
        asset_stage: "Aset",
        invalid_asset_index: "Format asset index tidak dikenal",
        invalid_java_version_format: "Format versi Java tidak dikenal",
        java_index_empty: "Indeks Java runtime kosong",
        invalid_java_runtime_data: "Format data Java runtime tidak dikenal",
        invalid_runtime_data: "Data runtime {} tidak valid",
        invalid_runtime_manifest: "Format manifest runtime tidak dikenal",
        runtime_manifest_no_files: "Manifest runtime tidak berisi file",
        failed_fetch_account_status: "Gagal mengambil info akun (status {}): {}",
        access_denied: "Anda menolak permintaan otorisasi.",
        open_page_code: "Buka {} lalu masukkan kode: {}",
        token_received_fetching_profile: "Token diterima, mengambil profil akun...",
        no_refresh_token: "Akun ini tidak memiliki refresh_token",
        login_request_denied: "Ely.by menolak permintaan login ({}): {}",
        wrong_credentials: "Kredensial salah.",
        unknown_auth_response: "Respons auth tidak dikenal",
        no_minecraft_profile: "Akun tidak memiliki profil Minecraft",
        no_client_token: "Akun tidak memiliki client token",
        invalid_token: "Token tidak valid.",
        refresh_failed: "Refresh gagal: {}. Silakan login ulang.",
        unknown_refresh_response: "Respons refresh tidak dikenal",
        invalid_avatar_image: "Avatar bukan gambar valid",
        no_data_dir: "Tidak dapat menentukan direktori data aplikasi",
        account_uses_2fa: "Akun ini memakai autentikasi 2FA.",
        enter_verify_code: "Masukkan kode verifikasi di halaman Ely.by.",
        java_mismatch: "Java {} tidak kompatibel dengan versi ini (butuh Java {}). Unduh runtime yang benar dari pengaturan Java.",
        java_mode_label: "Mode Java:",
        java_mode_auto: "Otomatis (deteksi sesuai versi)",
        java_mode_manual: "Manual (pilih path)",
        auto_java_desc: "Otomatis memilih Java yang tepat untuk versi Minecraft ini; bila tidak ada, runtime yang dibutuhkan akan diunduh.",
        browse: "Pilih...",
        open_logs_folder: "Buka Folder Log",
        open_folder: "Buka Folder",
        open_failed: "Gagal membuka folder: {}",
        game_dir_label: "Folder Minecraft:",
        game_dir_path_label: "Path folder:",
        game_dir_launcher: "Launcher (folder launcher saat ini)",
        game_dir_original: "Default (.minecraft launcher original)",
        game_dir_custom: "Baru (tentukan lokasi sendiri)",
        game_dir_hint: "Folder tempat saves, server, mod, dan config disimpan. Versi/libraries/assets tetap di folder launcher.",
        browse_folder: "Pilih Folder...",
        data_dir_label: "Folder Data Minecraft (versi, libraries, assets, runtime):",
        data_dir_choice: "Lokasi data:",
        data_dir_launcher: "Launcher (folder launcher saat ini)",
        data_dir_original: "Default (.minecraft launcher original)",
        data_dir_custom: "Baru (tentukan lokasi sendiri)",
        data_dir_path_label: "Path folder:",
        data_dir_hint: "Versi, libraries, assets, dan runtime instansi ini dipasang dan dibaca dari folder ini. Folder game (saves/server/mod) tetap diatur di bagian atas. Dipakai bersama launcher original bila memilih folder .minecraft.",
        data_dir_current: "Lokasi saat ini: {}",
        data_dir_changed: "Folder data Minecraft diubah.",
        vanilla_branding_label: "Brand & channel vanilla",
        vanilla_branding_hint: "Laporkan ke game sebagai launcher vanilla (brand & channel = vanilla).",
        delete_confirm_title: "Hapus instansi?",
        delete_confirm_body: "Instansi '{}' akan dihapus dari daftar.",
        delete_confirm_also_folder: "Hapus juga folder Minecraft instansi ini",
        delete_folder_locked: "Folder ini tidak dapat dihapus (dipakai bersama / milik launcher original).",
        folder_deleted: "Folder Minecraft dihapus.",
    };

    pub const EN: &'static Lang = &Lang {
        by: "By StievenW",

        nav_home: "Home",
        nav_versions: "Versions",
        nav_instances: "Instances",
        nav_accounts: "Accounts",
        nav_settings: "Settings",
        nav_console: "Console",

        active_version: "ACTIVE VERSION",
        memory: "MEMORY",
        installed: "Installed",
        not_installed: "Not installed",

        home_ready: "Ready.",
        waiting_task: "Waiting for the task to finish...",
        need_login_hint: "Sign in to your Ely.by account to play (Accounts menu).",
        need_version_hint: "Select a version first.",
        play: "PLAY",
        install: "INSTALL",
        stop: "STOP",
        active_account: "ACTIVE ACCOUNT",
        manage: "Manage",
        no_active_account: "No active account.",
        sign_in: "Sign in",
        mc_version: "MINECRAFT VERSION",
        status: "STATUS",

        search_versions: "Search versions...",
        reload: "Reload",
        releases_only_hint: "Showing releases only. Enable 'All versions' in Settings to see builds, betas and snapshots.",
        loading_versions: "Loading the version list...",
        empty_versions: "The version list is empty.",
        use_version: "Use",
        pick_version: "Install",
        client_mods: "CLIENT MODS",
        client_mods_mc: "Minecraft version:",
        client_mods_load: "Load list",
        failed_fetch_loaders: "Failed to load the loader list.",

        saved_accounts: "SAVED ACCOUNTS",
        no_saved_accounts: "No saved accounts.",
        remove: "Remove",
        refresh_token: "Refresh Token",
        activate: "Activate",
        active_badge: "ACTIVE",
        ely_oauth: "Ely.by (OAuth)",
        ely_password: "Ely.by (Password)",
        token_expired: "token expired",
        token_valid_min: "token valid for ~{} min",
        token_expires_on: "Expires {} ({} left)",
        unit_day: "d",
        unit_hour: "h",
        unit_min: "m",
        unit_sec: "s",
        add_account: "ADD ACCOUNT",
        oauth_title: "Login with Ely.by (OAuth)",
        oauth_desc: "Uses a verification code (device flow). The client ID is embedded in the launcher.",
        login_with_ely: "Login with Ely.by",
        login_ely_account: "Sign in with your Ely.by account",
        register_ely: "Don't have an Ely.by account? Register",
        offline_account: "Offline Account",
        offline_desc: "Requires signing in with an Ely.by account first.",
        offline_name: "Player name",
        add_offline: "Add Offline Account",
        offline_name_invalid: "Invalid player name (3-16 characters, no spaces).",
        offline_locked: "Locked - sign in with a valid Ely.by account first.",
        password_title: "Login with email / password",
        email_or_username: "Email or username",
        password: "Password",
        show_password: "Show password",
        fill_credentials: "Fill in email/username and password.",

        versions_label: "VERSION",
        show_all_versions: "Show all versions (builds, betas, snapshots)",
        show_custom_clients: "Show all complete custom clients",
        custom_clients_hint: "Lists client mods / custom clients installed in the launcher versions folder (outside the official Mojang list).",
        kind_custom: "custom",
        java_label: "JAVA",
        auto_download_java: "Auto-download a Java runtime if none is found",
        java_path: "Java path:",
        detect: "Detect",
        clear: "Clear",
        download_java_now: "Download Java Now",
        needs_java: "This version needs Java {}+",
        java_saved: "Java {} found and saved to settings.",
        java_not_found: "A suitable Java (Java {}+) was not found. Install Java or use auto-download.",
        launch_label: "LAUNCH",
        memory_label: "Memory:",
        resolution: "Resolution:",
        authlib_url_label: "authlib URL:",
        authlib_hint: "-javaagent authlib-injector argument",
        extra_jvm_args_label: "Extra JVM arguments:",
        extra_jvm_args_hint: "e.g. -Duser.language=en",
        reset_defaults: "Reset to Defaults",
        language_label: "LANGUAGE",
        language_choice: "App language:",
        indonesian: "Indonesia",
        english: "English",
        font_label: "FONT",
        font_choice: "App font:",
        font_monogram: "Monogram (Bitmap)",
        font_system: "Normal (System)",

        instances_title: "INSTANCES",
        new_instance: "New Instance",
        select: "Select",
        edit: "Edit",
        delete: "Delete",
        no_instances: "No instances yet.",
        no_instances_hint: "Create one to start playing.",
        instance_name: "Instance name:",
        save: "Save",
        cancel: "Cancel",
        name_taken: "Instance name already taken.",
        cannot_delete_last: "Cannot delete the last instance.",
        instance_created: "Instance created.",
        instance_updated: "Instance updated.",
        instance_deleted: "Instance deleted.",
        no_instance_selected: "Select or create an instance first.",
        switch_instance: "Switch",
        version_changed_reinstall: "Version changed, it will be installed when PLAY is pressed.",
        choose_instance: "Choose instance:",
        latest_instance: "Latest (Release)",
        latest_badge: "RELEASE - AUTO",
        latest_hint: "Automatically uses the newest release on every PLAY.",
        latest_no_edit: "Version cannot be changed (always the newest release).",
        delete_data: "Delete Data",
        check_repair: "Check & Repair",
        repairing: "Checking and repairing the version...",
        repair_ok: "Version complete and valid, nothing broken.",
        version_delete_title: "Delete version?",
        version_delete_body: "Version data '{}' (JSON, jar and version files) will be permanently removed. Continue?",
        tab_all: "All",
        tab_downloaded: "Downloaded",
        empty_downloaded: "No downloaded versions yet.",
        create_instance_hint: "Create your own instance to pick any version (Instances menu).",
        version_unavailable: "Version not available yet. Check your connection and reload the version list.",
        already_running: "HanaLauncher is already running. Close the existing instance first.",
        version_deleted: "Version data deleted.",
        latest_key_reserved: "The name 'latest' is reserved for the newest instance.",
        update_available: "New version available",
        update_available_body:
            "Version {} is available. Keep playing on the installed version or update now?",
        installed_current: "Currently installed version: {}",
        continue_playing: "Keep playing ({})",
        update_now: "Update now",

        console_clear: "Clear",
        auto_scroll: "Auto-scroll",

        toast_ok: "Success",
        toast_err: "Failed",
        toast_info: "Info",
        task_busy: "Another task is already running.",
        game_running: "Game is running (PID {}).",
        game_stopped: "Stopping game...",
        game_exited: "Game exited with code {}.",
        account_added: "Account added.",
        account_active: "Active account: {}",
        account_removed: "Account removed.",
        verify_page: "Enter the verification code on the Ely.by page.",
        copy: "Copy",
        open_verify_page: "Open verification page",
        oauth_auto: "Login completes automatically once the code is confirmed on that page.",
        login_cancelled: "Login cancelled.",
        twofa_title: "Two-factor authentication (2FA)",
        twofa_hint: "Enter the code from your authenticator app:",
        submit: "Submit",
        twofa_empty: "2FA code is empty.",
        select_version_first: "Select a version first.",
        login_required: "Sign in first to play (Accounts page).",
        stop_game: "Stopping game...",
        saved: "Settings saved.",
        save_failed: "Failed to save: {}",
        installing_version: "Installing version...",
        done_version: "Version installed.",

        version_picked: "Selected version: {}",
        starting: "Starting...",
        verify_win_title: "Login Ely.by - Verification",
        cannot_open_browser: "Cannot open the browser.",
        console_save: "Save Log",
        log_saved: "Log saved at {}",
        log_copied: "Log copied to clipboard.",

        init_failed: "Initialization failed: {}",
        fetching_versions: "Fetching the Minecraft version list...",
        found_versions: "Found {} versions.",
        login_success: "Logged in as {}",
        token_updated: "Token refreshed for {}",
        checking_latest: "Checking for the latest release version...",
        newer_available: "Newer version {} available (installed: {}).",
        choice_dialog_closed: "Version dialog closed, update cancelled.",
        continuing_version: "Continuing with version {}.",
        update_cancelled: "Version update cancelled.",
        no_active_instance_err: "No active instance",
        no_version_selected_err: "No version selected",
        java_too_old: "Detected Java (major {}) is too old for this version (needs {}), searching...",
        java_missing: "Java not found. Install Java {}+ or enable auto-download in Settings.",
        using_java: "Using Java {}: {}",
        repairing_install: "Version is not fully installed, repairing...",
        launch_args: "Launch arguments:",
        game_launched_pid: "Game launched (PID {}).",
        installing_version_log: "Installing version {}...",
        checking_assets: "Checking asset index '{}'...",
        java_runtime_installed: "Java runtime already installed: {}",
        downloading_java: "Downloading Java runtime {} (Java {}+)...",
        account_type_password: "{} (Ely.by - password)",
        account_type_oauth: "{} (Ely.by - OAuth)",

        failed_connect_ely: "Failed to reach the Ely.by token server",
        failed_fetch_account: "Failed to fetch Ely.by account info",
        failed_start_login: "Failed to start the Ely.by login (device code)",
        failed_refresh_token: "Failed to refresh the Ely.by token",
        failed_fetch_avatar: "Failed to download avatar",
        failed_read_avatar: "Failed to read avatar",
        login_failed: "Login failed: {}",
        code_expired: "Verification code expired. Please try logging in again.",
        login_denied: "Login denied: {}",
        failed_fetch_versions: "Failed to fetch the Minecraft version list",
        failed_read_versions: "Failed to read the version list",
        failed_download_version: "Failed to download version data {}",
        failed_parse_version: "Unknown version data format for {}",
        failed_download_authlib: "Failed to download authlib-injector",
        failed_open_native_jar: "Failed to open native jar",
        failed_java_version: "Failed to run java -version",
        cannot_read_java_version: "Cannot read the Java version",
        no_java_for_platform: "No Java runtime for platform {}",
        no_matching_runtime: "No matching runtime found",
        no_manifest_for: "No manifest for {}",
        failed_launch_game: "Failed to launch the game process",
        failed_wait_game: "Failed waiting for the game process",
        no_launch_args: "This version has no launch argument definition",
        failed_download: "Failed to download: {}",
        failed_read_response: "Failed to read response: {}",
        failed_save_download: "Failed to save {}",
        no_url_available: "No URL available",
        version_not_in_manifest: "Version {} not found in the Mojang version list",
        inherits_unsupported: "Version {} inherits another version (mod version) and is not directly supported.",
        asset_progress: "  Assets [{}/{}]",
        invalid_archive: "Native jar is not a valid archive",
        downloading_client_jar: "Downloading client jar...",
        extracting_natives: "Extracting native libraries...",
        server_status: "Server returned status {} for {}",
        sha1_mismatch: "SHA1 checksum mismatch for {} (expected {}, got {})",
        failed_read_bytes: "Failed to read response",
        all_urls_failed: "All URLs failed",
        asset_stage: "Assets",
        invalid_asset_index: "Unknown asset index format",
        invalid_java_version_format: "Unknown Java version format",
        java_index_empty: "Java runtime index is empty",
        invalid_java_runtime_data: "Unknown Java runtime data format",
        invalid_runtime_data: "Invalid runtime data for {}",
        invalid_runtime_manifest: "Unknown runtime manifest format",
        runtime_manifest_no_files: "Runtime manifest contains no files",
        failed_fetch_account_status: "Failed to fetch account info (status {}): {}",
        access_denied: "You denied the authorization request.",
        open_page_code: "Open {} then enter the code: {}",
        token_received_fetching_profile: "Token received, fetching the account profile...",
        no_refresh_token: "This account has no refresh_token",
        login_request_denied: "Ely.by denied the login request ({}): {}",
        wrong_credentials: "Wrong credentials.",
        unknown_auth_response: "Unknown auth response",
        no_minecraft_profile: "Account has no Minecraft profile",
        no_client_token: "Account has no client token",
        invalid_token: "Invalid token.",
        refresh_failed: "Refresh failed: {}. Please log in again.",
        unknown_refresh_response: "Unknown refresh response",
        invalid_avatar_image: "Avatar is not a valid image",
        no_data_dir: "Cannot determine the application data directory",
        account_uses_2fa: "This account uses 2FA.",
        enter_verify_code: "Enter the verification code on the Ely.by page.",
        java_mismatch: "Java {} is not compatible with this version (needs Java {}). Download the correct runtime from the Java settings.",
        java_mode_label: "Java mode:",
        java_mode_auto: "Automatic (matches the version)",
        java_mode_manual: "Manual (choose a path)",
        auto_java_desc: "Automatically picks the right Java for this Minecraft version; if none matches, the needed runtime is downloaded.",
        browse: "Browse...",
        open_logs_folder: "Open Log Folder",
        open_folder: "Open Folder",
        open_failed: "Failed to open folder: {}",
        game_dir_label: "Minecraft folder:",
        game_dir_path_label: "Folder path:",
        game_dir_launcher: "Launcher (current launcher folder)",
        game_dir_original: "Default (original launcher .minecraft)",
        game_dir_custom: "New (choose a location)",
        game_dir_hint: "Where saves, servers, mods and config are stored. Versions/libraries/assets stay in the launcher folder.",
        browse_folder: "Choose Folder...",
        data_dir_label: "Minecraft data folder (versions, libraries, assets, runtime):",
        data_dir_choice: "Data location:",
        data_dir_launcher: "Launcher (current launcher folder)",
        data_dir_original: "Default (.minecraft original launcher)",
        data_dir_custom: "New (choose a location)",
        data_dir_path_label: "Folder path:",
        data_dir_hint: "This instance's versions, libraries, assets and runtime are installed to and read from this folder. The game folder (saves/servers/mods) is still set above. Choosing the .minecraft folder shares it with the original launcher.",
        data_dir_current: "Current location: {}",
        data_dir_changed: "Minecraft data folder changed.",
        vanilla_branding_label: "Vanilla brand & channel",
        vanilla_branding_hint: "Report to the game as a vanilla launcher (brand & channel = vanilla).",
        delete_confirm_title: "Delete instance?",
        delete_confirm_body: "Instance '{}' will be removed from the list.",
        delete_confirm_also_folder: "Also delete this instance's Minecraft folder",
        delete_folder_locked: "This folder cannot be deleted (shared / owned by the original launcher).",
        folder_deleted: "Minecraft folder deleted.",
    };

    pub fn for_code(code: &str) -> &'static Lang {
        if code == crate::config::LANG_EN {
            Lang::EN
        } else {
            Lang::ID
        }
    }
}

use std::sync::Mutex;

/// Current UI language. Worker threads (console logs, install progress,
/// error messages) read this so the console never mixes Indonesian/English.
static CURRENT: Mutex<Option<&'static Lang>> = Mutex::new(None);

pub fn set_current(lang: &'static Lang) {
    if let Ok(mut c) = CURRENT.lock() {
        *c = Some(lang);
    }
}

pub fn current() -> &'static Lang {
    let guard = CURRENT.lock().unwrap();
    match *guard {
        Some(l) => l,
        None => &Lang::ID,
    }
}